### ISSUE TITLE
Metadata update - Implement bulk method in API for batch editing

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-api-py-minsdk#133]
## Context

Editing requests are too inefficient and destabilize the platform, even when they are sent asynchronously.

In the API source code, we can see there is a bulk method connected to the `POST /resources` routes:

https://github.com/isogeo/isogeo-api/blob/7fabd862d95dc117ea59cb2b6848c0c1df261c87/Api.V10/HttpRouteCollectionExtensions.cs#L161

### Source code

https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/Bulk.cs

https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/BulkAction.cs
https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/BulkTarget.cs
https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/BulkQuery.cs

### Functional

The best way to see bulk in action is to use the batch tag/edit button in app.isogeo.com.

----

## Implementation

Using the model of [*Prepared requests*](https://requests.readthedocs.io/en/master/user/advanced/#prepared-requests):

- [x] add related enums:
  - [x] Actions
  - [x] Targets
  - [x] Ignored Reasons
- [x] add related models:
  - [x] Bulk Request
  - [x] Bulk Report
- [x] add a dedicated module called Bulk with:
  - [x] a method `prepare` which can be called to add actions to perform later
  - [x] a method `send` to launch the final request with the consolidated data

### Script example

```python
# get catalogs and keywords to tag metadatas with
cata = isogeo.catalog.get(
    workgroup_id={group_uuid},
    catalog_id={catalog_uuid},
)

kwd = isogeo.keyword.get(keyword_id={keyword_uuid})

# prepare JSON
data = [
    {
        "action": "add",
        "target": "catalogs",
        "query": {
            "ids": [
                "{metadata_X_uuid}",
                "{metadata_Y_uuid}",
                "{metadata_Z_uuid}",
            ],
        },
        "model": [cata.to_dict()],
    },
    {
        "action": "add",
        "target": "keywords",
        "query": {
            "ids": [
                "{metadata_X_uuid}",
                "{metadata_A_uuid}",
                "{metadata_G_uuid}",
            ],
        },
        "model": [kwd.to_dict()],
    },
]

# send
req = isogeo.post(
    url="https://api.qa.isogeo.com/resources/",
    json=data,
    headers=isogeo.header,
    proxies=isogeo.proxies,
    verify=isogeo.ssl,
    timeout=isogeo.timeout,
)

# print(req.status_code)

# -- END -------
isogeo.close()  # close session
```

----

## Resources

- [Adding batch or bulk endpoints to your REST API](https://www.codementor.io/blog/batch-endpoints-6olbjay1hd)
- [Python Requests: prepared requests](https://requests.readthedocs.io/en/master/user/advanced/#prepared-requests)

**Comment by VianneyDoleans** [comment]
https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/Bulk.cs

https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/BulkAction.cs
https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/BulkTarget.cs
https://github.com/isogeo/isogeo-api/blob/master/Api.V10/Business/Bulk/BulkQuery.cs
