### ISSUE TITLE
[on-premises] rendre compatible avec une API non-SaaS

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-api-py-minsdk#250]
L’URL d’authentification est renseigné via l'argument d'instanciation `auto_refresh_url` de la classe **Isogeo** hérité de la classe **OAuth2Session**. Il est donc en théorie déjà possible de s'authentifier à une API non-SaaS avec le SDK Python.

En revanche, pour ce qui est des autres URLs, notamment v1.api.isogeo.com qui constitue la base des URLs de toutes les routes (hors authentification), le SDK Python est uniquement compatible avec la configuration SaaS. Seule l'API de prod et l'API de QA sont gérées et une partie des URLs de la solution sont générés par la méthode *set_base_url* du module **IsogeoUtils**. Il va falloir modifier ce fonctionnement en profondeur de sorte à permettre à l'utilisateur d'indiquer des URLs *customs*.

**Comment by SimonSAMPERE** [comment]
Le mode custom a été ajouté avec possibilité de renseigner des URLs d'API hors ceux de Prod ou de QA. Il passe tous les tests unitaire avec une API Local antérieure à celle de QA (sans évolutions sur les couches de service).

**Comment by SimonSAMPERE** [comment]
Sur l'environnement de Recette, le SDK parvient à interagir avec l'API installée sur la VM Windows server 2016 depuis la même VM, via les URL :
ISOGEO_API_URL=https://localhost:8011/
ISOGEO_ID_URL=https://localhost:8021/
et
ISOGEO_API_URL=https://v1.api.recette-isogeo.com/
ISOGEO_ID_URL=https://id.api.recette-isogeo.com/

La communication HTTPS fonctionne dans les deux cas lorsque le check du certificat SSL est désactivé, en revanche, lorsqu'il est activé, la connexion échoue avec l'erreur suivante : 
```
certificate verify failed: unable to get local issuer certificate
```
@LyesIsogeo  ça peut peut-être t'intéresser...

@emmanuelamicel, j'ai remarqué en me connectant à l'API la première fois qu'il n'existait aucun groupe de travail. En tous cas quand je listait les GT avec l'utilisateur admin-app, la liste était vide. J'ai pu en créer un donc pas de problème mais je sais pas si c'est conforme au comportement attendu dans l'environnement de recette.

**Comment by emmanuelamicel** [comment]
> @emmanuelamicel, j'ai remarqué en me connectant à l'API la première fois qu'il n'existait aucun groupe de travail. En tous cas quand je listait les GT avec l'utilisateur admin-app, la liste était vide. J'ai pu en créer un donc pas de problème mais je sais pas si c'est conforme au comportement attendu dans l'environnement de recette.

https://github.com/isogeo/isogeo-database-central/issues/11

Ce comportement est conforme aux spécifications qu'on a produites pour la création de la base de données dockerisée. Il serait intéressant d'écrire une sorte de manuel d'initialisation de l'environnement Isogeo une fois l'installation réussie : modification du mot de passe de l'administrateur admin-app, création d'un groupe de travail, création de nouvelles applications dans Manage, etc.

**Comment by SimonSAMPERE** [comment]
C'est noté merci @emmanuelamicel ! ça m'était sorti de la tête, bonne idée pour le manuel.

**Comment by SimonSAMPERE** [comment]
Pour redémarrer l'API on prem de recett :
1. Allumer les VM :
  * [windowsServer2016Recette](https://portal.azure.com/#@isogeo.fr/resource/subscriptions/82885610-5841-4749-8d71-46f56b643ad2/resourceGroups/ON-PREMISES/providers/Microsoft.Compute/virtualMachines/windowsServer2016Recette/overview)
  * [windowsServer2019Recette](https://portal.azure.com/#@isogeo.fr/resource/subscriptions/82885610-5841-4749-8d71-46f56b643ad2/resourceGroups/On-Premises/providers/Microsoft.Compute/virtualMachines/windowsServer2019Recette/overview)
  * [CentOsRecette1](https://portal.azure.com/#@isogeo.fr/resource/subscriptions/82885610-5841-4749-8d71-46f56b643ad2/resourceGroups/On-Premises/providers/Microsoft.Compute/virtualMachines/CentOsRecette1/overview)
2. Sur CentOsRecette1 : 
```
sudo -s
```
```
systemctl restart docker
```
```
cd ./on-premises-old
```
```
docker-compose up
```
